---
- name: Create a security group
  local_action: 
     module: ec2_group
     name: ec2_security_group
     vpc_id: "{{ vpc.vpc_id }}"
     description: Security Group for webserver Servers
     region: "{{ region }}"
     rules:
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 8900
         to_port: 8900
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0
     rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
  register: ec2_group_info

- name: create a ec2 instance 
  ec2:
    count: 1
    region: "{{ ec2.region }}"
    keypair: "{{ ec2.credentials }}"
    instance_tags: "{{ ec2.tags }}"
    image: "{{ ec2.image }}"
    instance_type: "{{ ec2.instance_type }}"
#    instance_profile_name: "{{ ec2.role | defaults('') }}"
    group_id: "{{ec2.security_group }}"
    vpc_subnet_id: "{{ ec2.subnet_id }}"
    assign_public_ip: no
    wait: yes
  register: ec2_out

- name: gather facts about ec2 instance
  ec2_facts:

- debug: var=ec2_out

- name: Add the new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: launched
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2_out.instances }}"

#- name: Wait for SSH
 # wait_for:
  #    host: "{{ item.private_ip}}"
   #   port: 22
    #  delay: 10
     # timeout: 320
     # state: started
 # with_items: "{{ ec2_out.instances }}"

